### ISSUE TITLE
wrong homepage link

### ISSUE THREAD

**Issue by mgcrea** [jimrhoskins/ngmodules.org#1]
ie. http://ngmodules.org/modules/angular-strap

**Comment by jimrhoskins** [comment]
Much appreciated. Deployed

**Comment by sirkitree** [comment]
Related: if you don't put http:// in front of the url for the homepage, it will give you a relative link. Can open a new issue if you prefer.

**Comment by jimrhoskins** [comment]
@sirkitree is there a location where that is the case?

**Comment by sirkitree** [comment]
I created my first here: http://ngmodules.org/modules/angular-directive.g-signin

When I neglected to prepend the http:// to the Homepagefield, this happened. I've since added it, but I suspect any would act this way.
