### ISSUE TITLE
Can't add a package: "We're sorry, but something went wrong."

### ISSUE THREAD

**Issue by slavafomin** [jimrhoskins/ngmodules.org#36]
Can't add a package from:
https://github.com/betsol/angular-input-locker

I'm getting the following message: `We're sorry, but something went wrong.`.

**Comment by nichtich** [comment]
I get the same error message. Filling out the submission form works, but the final step fails.

**Comment by uttesh** [comment]
same unable to submit a package 
https://github.com/uttesh/ngtimeago
https://github.com/uttesh/nggentle

I'm getting the following message: We're sorry, but something went wrong..

**Comment by andrew-cunliffe** [comment]
I have been getting this when trying to update the 'tags' field, clearing the tags field seems to allow submission of changes, but all tags are gone now, see: http://ngmodules.org/modules/angular-toolbelt

**Comment by uttesh** [comment]
@andrew-cunliffe  i could not get what tags your addressing, but i'm unable to submit my module...getting error as mention in previous comment..

**Comment by stormpat** [comment]
The problem stems from Github's OAuth, as Im not the author of ngmodules Im not sure how its implemented. The problem could be that theres old gem thats broken, or Github has deprecated some old api.

[edit]
IIRC there was some talk couple of months ago when the heart-bleed bug came, regarding OAuth tokens on Github.

[edit2]
After some research, the Github OAuth seems to respond OK, but there's something wrong with the callback.

**Comment by andrew-cunliffe** [comment]
@uttesh when you fill out the form there are a number of form fields (see below) its only when I populate that 'tags' field that I am unable to submit my module / changes - so I have had to empty the field making it harder to find my module when searching / filtering.
- Github URL
- Name
- Description
- Homepage
- **Tags**
- README

**Comment by uttesh** [comment]
@andrew-cunliffe  oh thnq for reply.....before that page only its throwing exception., i.e on click of submit module github button its redirecting to that error page.

**Comment by bimal1331** [comment]
Same, unable to submit a package
https://github.com/bimal1331/angular-images-loaded

Getting the following message: We're sorry, but something went wrong.. Doesn't work even on leaving the 'TAG' field empty as mentioned by others.

**Comment by jimrhoskins** [comment]
Sorry about this, hit heroku's db limits and had to upgrade. Should be working now
