### ISSUE TITLE
Cannot log in with my github account...

### ISSUE THREAD

**Issue by AlexCppns** [jimrhoskins/ngmodules.org#37]

**Comment by mistic100** [comment]
message is "We're sorry, but something went wrong."

**Comment by stormpat** [comment]
:+1:

**Comment by firecentaur** [comment]
Hi, I also can not log in with my github account

**Comment by jordanburke** [comment]
+1

**Comment by mathewbyrne** [comment]
+1

**Comment by abhikmitra** [comment]
+1 still happening

**Comment by jimrhoskins** [comment]
Sorry about this. Bumped up against heroku's db limits and had to upgrade the database. Should be working now

**Comment by AlexCppns** [comment]
Thank you @jimrhoskins !
