### ISSUE TITLE
recommend including a component.json and publishing to bower

### ISSUE THREAD

**Issue by dylang** [jimrhoskins/ngmodules.org#4]
`component.json` has become a standard way to describe client-side javascript components simular to Node's package.json or Ruby Gemfiles.

This leads to developers being able to use tools like [bower](http://twitter.github.com/bower/) to manage dependencies and keep client code updated 

Example `component.json`:

```
{
  "name": "angular-animations",
  "version": "1.0.0",
  "main": ["./path/to/app.css", "./path/to/app.js", "./path/to/sprite.img"],
  "dependencies": {
    "angular": "~1.0.3"
  }
}
```

And then users can type `bower install angular-animations` to get the files instead of manually downloading and copies files from github.

**Comment by lord2800** [comment]
Bower has instead settled on `bower.json` for their file name.

**Comment by dylang** [comment]
I'm closing this as we stopped using bower and instead use npm with browserify.
